function love.images()
    background = love.graphics.newImage("Pictures/GameBoard/Road.png")
    police = love.graphics.newImage("Pictures/Vehicles/Police.png")
    audi = love.graphics.newImage("Pictures/Vehicles/Audi.png")
    truck = love.graphics.newImage("Pictures/Vehicles/Truck.png")
    black_viper = love.graphics.newImage("Pictures/Vehicles/Black_viper.png")
    FinishLine = love.graphics.newImage("Pictures/GameBoard/FinishLine.png")
    StartLine = love.graphics.newImage("Pictures/GameBoard/StartLine.png")
    winner = love.graphics.newImage("Pictures/GameBoard/winner.jpg")
    boarder = love.graphics.newImage("Pictures/GameBoard/boarder.png")
    title = love.graphics.newImage("Pictures/GameBoard/title.png")
    Controls = love.graphics.newImage("Pictures/GameBoard/Controls.png")
    Menu = love.graphics.newImage("Pictures/GameBoard/Menu.png")
    MenuCars = love.graphics.newImage("Pictures/GameBoard/MenuCars.png")
end